#lang fsm


(define at-least-one-missing-dfa (make-dfa '(S A B C D E F G)
                                           '(a b c)
                                           'S
                                           '(S A B C D E F)
                                           '((S a C)
                                             (S b B)
                                             (S c A)
                                             (A a E)
                                             (A b D)
                                             (A c A)
                                             (B a F)
                                             (B b B)
                                             (B c D)
                                             (C a C)
                                             (C b F)
                                             (C c E)
                                             (D a G)
                                             (D b D)
                                             (D c D)
                                             (E a E)
                                             (E b G)
                                             (E c E)
                                             (F a F)
                                             (F b F)
                                             (F c G)
                                             (G a G)
                                             (G b G)
                                             (G c G))
                                           'no-dead))